### ISSUE TITLE
Python 2.7 installation is broken

### ISSUE THREAD

**Issue by mast** [micheles/decorator#102] opened 2021-04-02 13:30 UTC
Since you dropped python 2 support, you have to stop making universal wheels for this module, otherwise pypi is offering wrong version for python2 setups.
I see that this was addressed in commit 50fa96bf370146602b02ece8378cdafa9f57684f

Please push new version to pypi, otherwise we are having issues with installation on python2.

**Comment by exarkun** [comment] 2021-04-02 13:45
Tahoe-LAFS CI is now almost entirely failing because of this issue.

**Comment by kvitali** [comment] 2021-04-02 14:02
datadog and pytest packages install with pip2 fails because of this issue

**Comment by sdatko** [comment] 2021-04-02 14:33
Ech, a new release just before the Easter... I guess many people will get surprise after coming from Holidays/PTO ;-)

My tests for legacy builds are also failing due to this, though I am not even sure which package requires decorator as dependency.

**Comment by vphilippon** [comment] 2021-04-02 14:43
So I saw that the 5.0.1 release was uploaded with the proper `python_requires='>=3.5'`, which is good.
But it seems that the metadata didn't get sent to pypi.org though.

From my experience on other project getting that issue, I would bet this is caused by performing the upload using an old `setuptools` or `twine`. I'd suggest uploading a 5.0.2 using the latest `twine` available.

Hoping you'll be able to get out of the Python 2 realm with peace of mind with that done :)

**Comment by MrMino** [comment] 2021-04-02 15:34
@vphilippon damn, I nearly dug through half of pip codebase until I realized its not taken from `dist-info/METADATA`...

Thanks for the insight, would've saved me a lot of time if I read it first :smile: .

**Comment by altendky** [comment] 2021-04-02 15:49
The uploaded wheel file name lists `.py2.py3`.  This at least is decided on creation, not upload.  The Python version is also listed as 3.8 in the table.

https://pypi.org/project/decorator/5.0.1/#files
![image](https://user-images.githubusercontent.com/543719/113430522-541e6900-93a8-11eb-8d9c-a22a9701bb93.png)

I tried building several ways and didn't get `.py2` in the filename.

```
venv/bin/python -m build --wheel .
venv/bin/python setup.py bdist_wheel
venv/bin/pip wheel --no-deps --out-dir dist/ .
```

Of course that was with everything updated, so perhaps it is outdated `setuptools` as suggested.

**Comment by micheles** [comment] 2021-04-02 15:54
Uploaded release 5.0.2, let's hope this is the good one...

**Comment by altendky** [comment] 2021-04-02 15:56
```console
$ virtualenv -p python2 venv2                   
created virtual environment CPython2.7.18.final.0-64 in 122ms
  creator CPython2Posix(dest=/home/altendky/venv2, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/altendky/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==44.1.1, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
```

```console
$ venv2/bin/pip install decorator
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting decorator
  Using cached decorator-5.0.2.tar.gz (33 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/altendky/venv2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Hhmuuh/decorator/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Hhmuuh/decorator/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kKCLGk
         cwd: /tmp/pip-install-Hhmuuh/decorator/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Hhmuuh/decorator/setup.py", line 4, in <module>
        exec(open('src/decorator.py').read(), dic)  # extract the __version__
      File "<string>", line 162
        print('Error in generated code:', file=sys.stderr)
                                              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.3.1; however, version 20.3.4 is available.
You should consider upgrading via the '/home/altendky/venv2/bin/python -m pip install --upgrade pip' command.
```

**Comment by sdatko** [comment] 2021-04-02 15:57
I observe the same issue as @altendky on Python 2.7.5 with pip==20.3.4 and setuptools-44.1.1.

**Comment by mast** [comment] 2021-04-02 16:02
I confirm, same issue as @altendky for my setup as well

**Comment by micheles** [comment] 2021-04-02 16:13
Sorry if I am being thick, but the point of version 5 of the decorator module was to drop support for Python 2.7, so it is right if it does not work with it. python_requires and the universal flag are fixed, what else needs to be done to finally stop automatic build systems from trying to use version 5.X?

**Comment by vphilippon** [comment] 2021-04-02 16:15
Some from the pypi.org page (https://pypi.org/project/decorator/), you can see that `Requires: Python >=3.5` isn't shown in the metadata section.
An exemple that do: https://pypi.org/project/setuptools/

So that's a tell that _for some reason_, the metadata isn't sent to pypi.org. My best bet was the version of setuptools/twine used to upload the packages, but if @micheles you can assure us you used the latest version of `twine` to do the upload, then I don't know right now why it doesn't work. This is going to be some diging for sure.

**Comment by micheles** [comment] 2021-04-02 16:27
I have installed the latest twine and then run  `python setup.py sdist bdist_wheel upload` but perhaps it did not take twine, so now I tried again with
```
$ twine upload dist/*
```
Published 5.0.3

**Comment by altendky** [comment] 2021-04-02 16:28
Usually you run twine to run twine.  And build is the way to build stuff these days.  I rarely ever run `setup.py`.

**Comment by vphilippon** [comment] 2021-04-02 16:30
According to my test (and the pypi.org page) this worked :) . It seems you hapilly out of the Py2 realm!
Thanks for taking the time to fix this.

**Comment by micheles** [comment] 2021-04-02 16:32
So much has changed in the Python packaging ecosystem and since I do a release per year I was still following the old ways.
Thanks for the help to everybody involved, I am closing the issue.

**Closed by micheles** 2021-04-02 16:32 UTC
