### ISSUE TITLE
Deprecated Warning with Python 3.5

### ISSUE THREAD

**Issue by adryr83** [micheles/decorator#34] opened 2016-09-02 21:51 UTC
Hi,
I'm learning Python. I installed my first python program (Chatterbot 0.4.6) that uses NLTK. I installed last version of nltk (3.2.1), but it doesn't work for inspect.getargspec in decorators.py

How to solve this problem? I tried to install decorator.py and put it in nltk fold but nltk has a module named as decorators (not decorator).

Can you help me, please?

**Comment by micheles** [comment] 2016-09-03 14:45
A deprecation warning is a non-issue, it is just a warning. I will remove
it in future versions of the decorator module, bit it is not urgent at all.

**Comment by rgommers** [comment] 2016-09-03 22:21
This is a duplicate of gh-9. @adryr83 you can just use ``warnings.filterwarnings`` in your own code (until it's fixed here and NLTK has taken over that fix) if the warnings bothers you.

**Comment by adryr83** [comment] 2016-09-04 06:36
Thanks a lot to everybody!

Adri

Il 04/Set/2016 00:21, "Ralf Gommers" <notifications@github.com> ha scritto:

**Comment by micheles** [comment] 2017-06-03 13:58
I do not see any warning with Python 3.6, so I will do nothing for the moment.

**Closed by micheles** 2017-06-03 13:58 UTC
