### ISSUE TITLE
args or kwargs

### ISSUE THREAD

**Issue by AdrianTeng** [micheles/decorator#2] opened 2015-03-16 23:56 UTC
First off, glad you are updating the project again!

I was actually trying to fix [this issue](https://code.google.com/p/micheles/issues/detail?id=7&can=1) at your old repo and saw you have closed the issue as "not an issue".

To reiterate the problem, here is a test that shows the issue:

    @decorator
    def test_decorator(f, *args, **kwargs):
        assert args == (1, 2)  # <---- failed here, args is (1,2,3,4) instead
        assert kwargs == dict(c=3, d=4, e=5)  # <---- kwargs is dict(e=5)
        return f(*args, **kwargs)

    @test_decorator
    def foo(a, b, c=-1, d=-2, **kwargs):
        assert kwargs['e'] == 5
        return a, b, c, d

    assert foo(1, 2, c=3, d=4, e=5) == (1, 2, 3, 4)

In this case, `args` giving `(1,2,3,4)` is the surprising behaviour. In fact, if we use vanilla python, we would have `args = (1, 2)` and `kwargs = dict(c=3, d=4, e=5)`:

    def decor(f):       
        def wrapper(*args, **kwargs):
            print args, kwargs
            return f(*args,**kwargs)
        return wrapper

    @decor              
    def foo(a, b, c=-1,d=-2, **kwargs):
        pass

    foo(1,2,c=3,d=4,e=5)

    > (1, 2) {'c': 3, 'e': 5, 'd': 4}

Of `foo`'s parameters, I believe `a`, `b`, `c`, and `d` are called [_positional-or-keyword_ parameters](https://docs.python.org/3/glossary.html#term-parameter). IMHO we should do the _least_ surprising behaviour here, and put parameters that has default to be placed in `kwargs`.

**Comment by AdrianTeng** [comment] 2015-03-16 23:57
Also, I'm a few days away from making a fix. If you are happy I'll make a pull request later this week.

**Comment by micheles** [comment] 2015-03-18 12:41
I am sorry, but this is still a won't fix. You have discovered an error of the wrapper technology, which is missing up default arguments and keyword arguments. The decorator module is doing the right thing, by keeping them separated. The proof:

```python
import inspect
def foo(a, b, c=-1, d=-2, **kwargs): pass
print inspect.getargspec(foo)
ArgSpec(args=['a', 'b', 'c', 'd'], varargs=None, keywords='kwargs', defaults=(-1, -2))
```

`c` and `d` are not keyword arguments and must stay in the `args` group. The decorator module is doing the right thing, the wrapper approach is failing. The decorator module was designed to fix this error.

**Closed** 2015-03-18 12:42 UTC

**Comment by kylegibson** [comment] 2017-12-28 04:37
I was baffled by this problem as well. Here's what I wanted to do:

```python
def decorate_a_func(path):
    def _decorate(func, *args, **kwargs):
        baz = kwargs.get('baz')   # This didn't work as expected
        if baz:
            pass
        return func(*args, *kwargs)
    return decorator(_decorate)

@decorate_a_func(path=PATH)
def do_a_thing(foo, bar, baz):
    pass

do_a_thing(
    foo=123,
    bar=456,
    baz=True,
)

```

At the highlighted line above, kwargs was empty, and args was equal to (123, 456, True)

One solution is to do the following:

```python
baz = args[2]
```

This is probably fine if you don't mind the decorator being tightly coupled with the function(s) that it decorates, since now the decorator depends on that argument always being in the third position. That doesn't seem very ideal to me.

Alternatively, you can use inspect to build a dictionary of named arguments:

```python
import inspect
def decorate_a_func(path):
    def _decorate(func, *args, **kwargs):
        func_spec = inspect.getargspec(func)
        named_args = dict(zip(func_spec.args, args))
        baz = named_args.get('baz')
        if baz:
            pass
        return func(*args, *kwargs)
    return decorator(_decorate)
```

That works as expected, but seems like overkill. 

Is there a better solution to this scenario?
